modLoader = "javafml"
loaderVersion="[0,)"
license = "MIT"

[[mods]]
modId = "graphene"
version = "1.5.0"
displayName = "Graphene"
authors = "CarbonMC, ZCRAFT"
logo = "logo.png"

description = '''One of the best optimization mods'''

[[dependencies.graphene]]
modId = "minecraft"
mandatory = true
versionRange="[1.7.10,1.22]"
ordering = "NONE"
side = "BOTH"

[[dependencies.graphene]]
modId = "cloth_config"
mandatory = false
versionRange="0.0.1"
ordering = "NONE"
side = "CLIENT"
